name: Manual Run
on: [workflow_dispatch]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        run: npm install
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          start: npm run cy:run